name: Meson

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt install meson ninja-build libgtk-3-dev -y

    - name: Setup Build directory
      run: meson setup build
    
    - name: Build Project
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ninja
